version: "2"
services:
  server:
    image: sheetalagarwal/cryptdash_server
    container_name: cryptdash_server
    restart: always
    ports:
      - "5000:5000"
    links:
      - mongo
    volumes:
      - ./server:/usr/src/app
  client:
    image: sheetalagarwal/cryptdash_client
    container_name: cryptdash_client
    restart: always
    # stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"