---
- name: Deploy docker images
  hosts: client1
  vars_files:
  - ./server/env-enc.yml
  gather_facts: yes
  become: yes
  tasks:
    - name: Copy Docker Compose file from host machine to remote host
      copy:
        src: ./docker-compose.yml
        dest: ./

    - name: Replace Jinja2 template with decrypted env var into env.yml file
      template:
        src: server/env.j2
        dest: env.yaml


    # Now we actually run the Docker containers 
    # Detached mode is required, otherwise Jenkins build never exits
    # even though the docker-compose up command has successfully executed
    - name: Run the pulled Docker images in detached mode
      command: docker-compose up -d --build

    - name: copy env.yml to server docker container
      command: docker cp env.yaml cryptdash_server:/usr/src/app/env.yaml

    - name: Prune the dangling Docker images
      command: docker image prune --force